### ISSUE TITLE
[redesign-2021]  - ECD Tools Website Refresh

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/ecdtools.eclipse.org#91] opened 2021-02-03 19:21 UTC
This is a top-level bug for tracking the ECD Tools Website Refresh project.

This bug will be used to post updates about the project and discuss top-level issues. 

The plan is to breakdown this project into smaller issues. I plan on creating these new issues in the next few days.

Design File: 
https://www.dropbox.com/s/uu2ilbtrguehpy7/EXC201007_Eclipse_Cloud_Website_Rev12.xd?dl=0

Navigation: 
https://docs.google.com/spreadsheets/d/1TTevxsz6Fo4GyxqBctkuB-6ucr6hOdearrvEyFtyeJQ/edit?usp=sharing

Invision Link: 
https://invis.io/5C10DOVC3QTG

**Comment by chrisguindon** [comment] 2021-03-30 18:14
@brianking and Clark,

I broke down the website re-design into smaller deliverables:
https://github.com/EclipseFdn/ecdtools.eclipse.org/projects/2

 Can you please review our issues and let us know if we forgot anything important. 

Please feel free to add more information on each issue! I hoping that we can start implementing this project in April.

**Comment by chrisguindon** [comment] 2021-03-30 18:16
@ericpoirier Can you review the design files and let us know if you need anything else from excentric?

**Comment by ericpoirier** [comment] 2021-03-30 18:37
> @ericpoirier Can you review the design files and let us know if you need anything else from excentric?

From what I can see, they have only provided an .xd file which I don't have the software the open.

It would be preferable to get all the graphical elements in either jpg or png format. I'm thinking things like: background images, icons, pictures and logos. I don't think we need jpg or png files for elements that are reproducible in CSS.

Also it would be good to know the Font that they used.

**Comment by chrisguindon** [comment] 2021-03-30 18:39
@excentrickristy is this something that your team can provide?

**Comment by chrisguindon** [comment] 2021-03-30 18:40
@ericpoirier Is it correct for me to assume that we would be to buy you a license for https://www.adobe.com/ca/products/xd.html to work with these files?

**Comment by ericpoirier** [comment] 2021-03-30 18:46
> @ericpoirier Is it correct for me to assume that we would be to buy you a license for https://www.adobe.com/ca/products/xd.html to work with these files?

From what I understand, it's not possible to open XD in Photoshop which is what I currently have.

**Comment by chrisguindon** [comment] 2021-03-30 18:51
@ericpoirier I understand. Let's see if it's possible for  @excentrickristy to export all the images for us. If not, I will look at getting you a license for it.

Another solution might be to ask @meKokabi.

@meKokabi,

is it possible for you to export all the images that we need to implement this redesign?
https://www.dropbox.com/s/uu2ilbtrguehpy7/EXC201007_Eclipse_Cloud_Website_Rev12.xd?dl=0

**Comment by chrisguindon** [comment] 2021-03-30 19:52
@meKokabi Thanks for the info! I will reach out to @excentrickristy and see what they can do about that!

**Comment by meKokabi** [comment] 2021-03-30 19:53
My pleasure!

**Comment by meKokabi** [comment] 2021-03-30 23:41
@chrisguindon @ericpoirier @shanda-eclipse  Kristy is absolutely right, I am a heavy XD user, and love the platform. however as you notice you need to export the assets one by one and for a large file like this with at least thousands of layers....?😳 the professional practice would never suggest XD for the final deliverable.  
But no worries,😊 I've done it. Exported and categorized assets to subfolders to make your job easier @ericpoirier. Also make screenshots of the artboards/pages for our reference so if you find any missing assets it would be easy for both of us to find it. 
 Banner images have been multiplied with a blue light transparent layer which I added that as well, in case. We might need to export it to photoshop and make a single jpg file. 
Here You Are:
Artboards: 
![Home](https://user-images.githubusercontent.com/75500459/113069680-e5b28e80-918e-11eb-991d-d4eedc8cc031.png)
![Open VSX Poject Page – 6](https://user-images.githubusercontent.com/75500459/113069689-e9deac00-918e-11eb-9d00-076b3f7c0845.png)
![VSX Marketplace Product page@2x](https://user-images.githubusercontent.com/75500459/113069703-eea36000-918e-11eb-85c1-d456368111e9.png)
<img width="1098" alt="Screen Shot 2021-03-30 at 5 32 53 PM" src="https://user-images.githubusercontent.com/75500459/113069721-f8c55e80-918e-11eb-840d-440c73ea7f51.png">
![Open VSX Poject Page – 6@2x](https://user-images.githubusercontent.com/75500459/113069730-fcf17c00-918e-11eb-994b-5082dbf9a3df.png)
![Adopters](https://user-images.githubusercontent.com/75500459/113069736-febb3f80-918e-11eb-8c0e-599a10148180.png)
![Community](https://user-images.githubusercontent.com/75500459/113069743-00850300-918f-11eb-9a10-702c6be91426.png)
![Home](https://user-images.githubusercontent.com/75500459/113069749-05e24d80-918f-11eb-9c2f-0a6b14ec0b56.png)

 Assets including subfolders logos, icons, headshots, charts, banners:
[logos.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6232787/logos.zip)
[Icons.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6232789/Icons.zip)
[Headshots.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6232791/Headshots.zip)
[chart.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6232793/chart.zip)

**Comment by meKokabi** [comment] 2021-03-30 23:59
Here is the images folders:
[images1.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6232840/images1.zip)
[banners. A 2.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6232843/banners.A.2.zip)
[banner B.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6232846/banner.B.zip)
[images 3.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6232863/images.3.zip)
[3D icons 2.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6232876/3D.icons.2.zip)
[HomeMidPageImage.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6232884/HomeMidPageImage.zip)
[images8.zip](https://github.com/EclipseFdn/ecdtools.eclipse.org/files/6232909/images8.zip)

**Comment by chrisguindon** [comment] 2021-04-06 21:09
Excentric send me an email on the 31 with the latest design:
https://www.dropbox.com/s/6jx9kr94a1pqova/EXC201007_Eclipse_Cloud_Website_Rev13.xd.zip?dl=0

@shanda-eclipse My understanding is that we will need @meKokabi to work on the files before we can get started on the site.

**Comment by ericpoirier** [comment] 2021-04-26 15:33
Updated designs have been provided to us. I added them to the Drive[1] and went through the provided PDF to check what changed and what assets would need to be re-exported as images for web.

@meKokabi Can you have a look at the following list and export the updated elements? Thanks.

Here is a list of the assets that will need to be re-exported from the updated design:

**Home page**
- Whats new icons
- open Source Community Driven background image

**About page**
- background images
- Big icon

**Community page**
- Top Background image
- icons

**Adopters page**
- Top Background image

**Projects page**
- Top background image

**Join Us page**
- Background images
- icons

**Videos page**
- Top Background image
- Videos images

**Open VSX home page**
- Contact us background images

**Comment by ericpoirier** [comment] 2021-04-27 13:40
Mehrnaz added the new files at the following location:
https://drive.google.com/drive/folders/1PvHgU3lHBi6ORNnCNoNrvB3qxhlunhFB

**Comment by meKokabi** [comment] 2021-04-29 09:42
Hello.
The requested new files have been uploaded and stored here:
https://drive.google.com/drive/folders/1PvHgU3lHBi6ORNnCNoNrvB3qxhlunhFB

**Comment by ericpoirier** [comment] 2021-05-14 13:59
As I was working on the redesign of the home page, we decided this week that it would be a good idea for me to create a schedule of when I would create the different pages.

Here is the schedule I created for myself to give you an idea of the progress:
https://docs.google.com/document/d/1uPtH0miKIwVSjCLuhwHSewiGi_VtSWBv57Nnun4WriY/edit

Let me know if you have any questions.

Thanks!

**Comment by brianking** [comment] 2021-05-17 11:29
That schedule looks good to me @ericpoirier, thanks for the heads up. The only change I suggest, unless there is a good reason otherwise, if to move the Open VSX page from 2nd down to the end of the list.

/cc @croundy

**Comment by ericpoirier** [comment] 2021-05-17 12:30
> That schedule looks good to me @ericpoirier, thanks for the heads up. The only change I suggest, unless there is a good reason otherwise, if to move the Open VSX page from 2nd down to the end of the list.
> 
> /cc @croundy

Ok no problem, I thought to add at the top of my list because it a rather big page to build but I can put it at the end.

**Comment by ericpoirier** [comment] 2021-09-24 13:37
Closing this issue since we launched the redesign yesterday.

**Closed by ericpoirier** 2021-09-24 13:37 UTC
Labels: redesign
