### ISSUE TITLE
[redesign-2021] - open-vsx project page

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/ecdtools.eclipse.org#111] opened 2021-03-30 18:08 UTC
As previously noted, the new design is available here:
#91

open-vsx project page:
https://projects.invisionapp.com/share/5C10DOVC3QTG#/screens/446432557

**Deliverables:**

The data must be fetched from our API:
https://api.eclipse.org/#tag/Projects

We will need to determine what data is missing from our API and implement those changes. We don't want to manually update this page.

- [x] Jumbotron
- [x] About section
- [x] Who involved (PL and Committers)
- [x] Committers
- [ ] Contribution Activity / Companies involved
- [ ] Contact form -> I expect this to be an embed hubspot form.

**Comment by ericpoirier** [comment] 2021-07-13 14:32
@croundy @brianking where on the ECDtools project's page should we link the OpenVSX project page?

Can we update the "Get Started" link to point to this new page instead of projects.eclipse.org?

Thanks.

**Comment by brianking** [comment] 2021-07-13 15:24
> @croundy @brianking where on the ECDtools project's page should we link the OpenVSX project page?
> 
> Can we update the "Get Started" link to point to this new page instead of projects.eclipse.org?

I don't think we thought about this yet!

My 2c ... The PMI pages are important, so I think we should leave 'Get Started' as-is (although I am not sure if that is the right label). I would add a separate 'More Information' link.

**Comment by ericpoirier** [comment] 2021-07-13 15:37
> > @croundy @brianking where on the ECDtools project's page should we link the OpenVSX project page?
> > Can we update the "Get Started" link to point to this new page instead of projects.eclipse.org?
> 
> I don't think we thought about this yet!
> 
> My 2c ... The PMI pages are important, so I think we should leave 'Get Started' as-is (although I am not sure if that is the right label). I would add a separate 'More Information' link.

Ok I'm going to leave the current links as is and if you'd like to update the links text, you let me know.

I'll add a "More Information" link in the Open VSX block.

Thanks!

**Comment by croundy** [comment] 2021-07-13 20:04
> > @croundy @brianking where on the ECDtools project's page should we link the OpenVSX project page?
> > Can we update the "Get Started" link to point to this new page instead of projects.eclipse.org?
> 
> I don't think we thought about this yet!
> 
> My 2c ... The PMI pages are important, so I think we should leave 'Get Started' as-is (although I am not sure if that is the right label). I would add a separate 'More Information' link.

The "Get Started" link is meant to link to the project page. As Brian mentioned, "Get Started" may or may not be the right text. Let's change it to "Learn More"

**Comment by ericpoirier** [comment] 2021-07-14 19:10
@croundy @brianking, The Open VSX page is now on staging.

https://deploy-preview-149--eclipsefdn-ecdtools.netlify.app/projects/
https://deploy-preview-149--eclipsefdn-ecdtools.netlify.app/projects/open-vsx

I did not implement the contact form since we can't implement forms with hugo but let me know if you'd like to add a block containing contact links.

Also you will notice that we are missing the following data from our API:

Project Lead/Committer:
- Bio
- Picture

@chrisguindon, These could be available through the user_profile api to which we have the url from the project API but that would mean we have to do an API call for each users on the page.

**Comment by chrisguindon** [comment] 2021-07-14 20:10
> I did not implement the contact form since we can't implement forms with Hugo but let me know if you'd like to add a block containing contact links.

My expectation is that we would use a Hubspot form if we need a contact form on the page. 

@brianking Can you provide that for us? I think you need to ask Shada to create one for you.

> @chrisguindon, These could be available through the user_profile api to which we have the url from the project API but that would mean we have to do an API call for each users on the page.

That's exactly what we need to do. Let's create a module in solstice-assets that allow us to fetch the profile of a user from our API and display the information that we need such as their image.

I think this is something that we will need on all of our sites.

**Comment by ericpoirier** [comment] 2021-09-23 18:16
The implementation of the Open VSX project page is now on production and all the requested elements have been done at the exception of:

Contribution Activity / Companies involved
- We decided to remove this block since its was intended to contain dynamic content which we wouldn't have time to implement.

Contact form -> I expect this to be an embed hubspot form.
- We decided to remove this form since its not possible to manage forms in Hugo. That being said, we could add a form that is managed in Hubspot like we did for the Join Us page:
https://ecdtools.eclipse.org/membership/join-us/

I'll be closing this issue but please let me know if the contact form is something that needs to be implemented and I'll open a new issue to track that update.

Thanks.

**Closed by ericpoirier** 2021-09-23 18:16 UTC
Labels: redesign
